![ngo_project_image](ngo_project_image.jpg)

GoodThought NGO has been a catalyst for positive change, focusing its efforts on education, healthcare, and sustainable development to make a significant difference in communities worldwide. With this mission, GoodThought has orchestrated an array of assignments aimed at uplifting underprivileged populations and fostering long-term growth.

This project offers a hands-on opportunity to explore how data-driven insights can direct and enhance these humanitarian efforts. In this project, you'll engage with the GoodThought PostgreSQL database, which encapsulates detailed records of assignments, funding, impacts, and donor activities from 2010 to 2023. This comprehensive dataset includes:

- **`Assignments`:** Details about each project, including its name, duration (start and end dates), budget, geographical region, and the impact score.
- **`Donations`:** Records of financial contributions, linked to specific donors and assignments, highlighting how financial support is allocated and utilized.
- **`Donors`:** Information on individuals and organizations that fund GoodThought’s projects, including donor types.

Refer to the below ERD diagram for a visual representation of the relationships between these data tables:
<img src="erd.png" alt="ERD" width="50%" height="50%">


You will execute SQL queries to answer two questions, as listed in the instructions. Good luck!

In [36]:
-- highest_donation_assignments
select a.assignment_name, a.region, round(sum(d.amount),2) as rounded_total_donation_amount, ds.donor_type
from donations d
join assignments a on d.assignment_id = a.assignment_id
join donors ds on d.donor_id = ds.donor_id
group by a.assignment_name, a.region, ds.donor_type
order by round(sum(d.amount),2) desc
limit 5

   assignment_name region  rounded_total_donation_amount    donor_type
0  Assignment_3033   East                        3840.66    Individual
1   Assignment_300   West                        3133.98  Organization
2  Assignment_4114  North                        2778.57  Organization
3  Assignment_1765   West                        2626.98  Organization
4   Assignment_268   East                        2488.69    Individual

In [37]:
with cte as (select assignment_id, count(donation_id) as num_total_donations
	from donations 
	group by assignment_id),

cte2 as (select assignment_name, region, impact_score, cte.num_total_donations,
	row_number () over (partition by region order by impact_score desc) as rank_per_region
from assignments a 
join cte on a.assignment_id = cte.assignment_id
where cte.num_total_donations > 0)

select assignment_name, region, impact_score, num_total_donations 
from cte2 
where rank_per_region = 1
order by region

   assignment_name region  impact_score  num_total_donations
0   Assignment_316   East         10.00                    2
1  Assignment_2253  North          9.99                    1
2  Assignment_3547  South         10.00                    1
3  Assignment_2794   West          9.99                    2

In [3]:
-- Explore the data in the table
SELECT *
FROM public.donors
LIMIT 50

    donor_id donor_name    donor_type
0          1    Donor_1    Individual
1          2    Donor_2  Organization
2          3    Donor_3    Individual
3          4    Donor_4  Organization
4          5    Donor_5  Organization
5          6    Donor_6     Corporate
6          7    Donor_7    Individual
7          8    Donor_8     Corporate
8          9    Donor_9    Individual
9         10   Donor_10    Individual
10        11   Donor_11    Individual
11        12   Donor_12     Corporate
12        13   Donor_13  Organization
13        14   Donor_14     Corporate
14        15   Donor_15     Corporate
15        16   Donor_16    Individual
16        17   Donor_17  Organization
17        18   Donor_18  Organization
18        19   Donor_19  Organization
19        20   Donor_20  Organization
20        21   Donor_21    Individual
21        22   Donor_22  Organization
22        23   Donor_23    Individual
23        24   Donor_24    Individual
24        25   Donor_25  Organization
25        26   Donor_26     Corporate
26        27   Donor_27    Individual
27        28   Donor_28     Corporate
28        29   Donor_29    Individual
29        30   Donor_30  Organization
30        31   Donor_31  Organization
31        32   Donor_32     Corporate
32        33   Donor_33    Individual
33        34   Donor_34  Organization
34        35   Donor_35  Organization
35        36   Donor_36  Organization
36        37   Donor_37    Individual
37        38   Donor_38     Corporate
38        39   Donor_39    Individual
39        40   Donor_40     Corporate
40        41   Donor_41     Corporate
41        42   Donor_42    Individual
42        43   Donor_43     Corporate
43        44   Donor_44    Individual
44        45   Donor_45    Individual
45        46   Donor_46    Individual
46        47   Donor_47  Organization
47        48   Donor_48  Organization
48        49   Donor_49     Corporate
49        50   Donor_50    Individual